name: Build and Publish Node Image

on:
  workflow_dispatch:
  push:
    branches:
      - main
    paths:
      - "/src/**"

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Compile WebAssembly
        run: ./build-wasm.sh
